### PR TITLE
Monterey

### PR DESCRIPTION
**Pull request by zearp**
- Moving to Mac mini SMBIOS by default as it supports all macOS versions including Monterey
- The higher iGPU base clock is not an issue IMHO, I notice no difference in temps or performance
- Update README to reflect SMBIOS changes; put up a notice and make user pick SMBIOS when generating serials

Cleaning up the config and README are also on my list but not high priority, maybe split the whole thing up in easier to digest sections. It has a lot of information, not all in the most sensible place.

All in all the transition should be smooth for those who already have a config setup and only those who want to run Monterey need to change SMBIOS in their existing config. In the worst case someone who uses iCloud has to log out from iCloud and the iMessage/Facetime apps, generate new serials add them to the config and reboot.

### CODE REVIEW

**Comment by zearp** [comment]
I guess might as well make the change. Seems very stable so far, got some Xcode bugs that's about it. Dare I say Monterey is a lot smoother than Big Sur already and that's not due to the higher base clocks of the iGPU haha. It's the same when using iMac15,1 and Monterey with the lower base clock.

With the change the are no worries that updates won't install properly without patching or disabling compatibility checks all the time or every time you need to install updates/(re)install when Monterey drops in a few months. Beta 1 feels like a public beta already to be honest. Plus anyone can opt to use the iMac ones to stop update nags or just run with the checks disabled if they so please.

I think it's for the best and hopefully gets another update before no more Haswell Macs get the latest macOS. Then we can just the legacy installer patchers made for real Macs and then use that patched installed + EFI to install whatever future macOS versions, if there's no better ways by then.

Let me know here or in an issue if you run into anything.

**Comment by davidAlaBer** [comment]
Hello @zearp
I still don't have the Monterey public beta. Please can you make an update guide for people like me (9020 iMac15,1, Big Sur, external GPU, that works like charm). I don't want to mess things up as it is my working machine. Please...

**Comment by zearp** [comment]
@davidAlaBer Your machine will work fine, you can either disable compatibility checks or change SMBIOS. The first is easiest but may result in updates not installing properly ad other weird issues caused by using an SMBIOS Monterey doesn't "know" anymore.

The preferred way is to move SMBIOS. First sign out from iMessage/FaceTime and iCloud if you use those, open the apps to log out as logging out from just iCloud won't always log you out from iMessage/FaceTime as well.

Make a backup of your current EFI, download the latest release from here and put that in place of you EFI just like before. Generate new "invalid" serials to put in the config and also move over any other settings you changed from the default repo config, like your ethernet mac address  and dGPU things. It should all work just like in Big Sur/Catalina. 

If you tried and get stuck or things don't work, post a zipped version of you EFI that works lie a charm and I'll have a look at it. In theory just the things you changed from the default config before need to be changed, just like updating the EFI normally. The only difference is that we use another SMBIOS.

I been running the developer beta on my test 7020 and its working a lot smoother and nicer than Big Sur ever did on here. To me Big Sur is Apple's Windows ME or Vista, a failure. Specially when compared to how much better the first beta of Monterey runs on the same hardware.

Let me know how you get on!

PS: You can stay on Big Sur or Catalina if you so wish. I use the SMBIOS to stop update nags mostly. Check the updated SMBIOS section in on the repo. I keep my "main" 7020's on Catalina cuz its been proven to be super stable since I started this repo. Been using it daily and have only moved my test/builds 7020 to Monterey, which is performing great too. Including VMWare Fusion machines running and some development work.

**Comment by zearp** [comment]
@davidAlaBer Your machine will work fine, you can either disable compatibility checks or change SMBIOS. The first is easiest but may result in updates not installing properly and/or other weird issues caused by using an SMBIOS Monterey doesn't "know" anymore. The preferred way is to move SMBIOS, the Mac mini 7,1 is the only Haswell system to get Monterey.

First sign out from iMessage/FaceTime and iCloud if you use those, open the apps to log out as logging out from just iCloud won't always log you out from iMessage/FaceTime as well.

Make a backup of your current EFI, download the latest release from here and put that in place of you EFI just like before. Generate new "invalid" serials to put in the config and also move over any other settings you changed from the default repo config, like your ethernet mac address  and dGPU things. It should all work just like in Big Sur/Catalina. 

If you tried and get stuck or things don't work, post a zipped version of you EFI that works lie a charm and I'll have a look at it. In theory just the things you changed from the default config before need to be changed, just like updating the EFI normally. The only difference is that we use another SMBIOS.

I been running the developer beta on my test 7020 and its working a lot smoother and nicer than Big Sur ever did on here. To me Big Sur is Apple's Windows ME or Vista, a failure. Specially when compared to how much better the first beta of Monterey runs on the same hardware.

Let me know how you get on!

PS: You can stay on Big Sur or Catalina if you so wish. I use the SMBIOS to stop update nags mostly. Check the updated SMBIOS section in on the repo. I keep my "main" 7020's on Catalina cuz its been proven to be super stable since I started this repo. Been using it daily and have only moved my test/builds 7020 to Monterey, which is performing great too. Including VMWare Fusion machines running and some development work.

**Comment by davidAlaBer** [comment]
Pretty clear now! I will try asap and inform you!

**Comment by davidAlaBer** [comment]
Hi @zearp!
Everything seems OK after update except for:

1. When boot:

OC: Missing boot path
BS: Failed to start OpenCore Image - Invalid Parameter
BS: Failed to start OpenCore from disk - Invalid Parameter

2. Lost Graphical boot menu 

3. When I try to download Beta it doesn't show in Apple website

**Comment by davidAlaBer** [comment]
I managed to download the Monterey Beta, not installed yet.

Worried about the issue 1 when booting

**Comment by davidAlaBer** [comment]
Kernel Panic after fail crash.
Now Monterey running fine after reboot- Good feeling. Higher temperature maybe?

Still worried about OC warning :

OC: Missing boot path
BS: Failed to start OpenCore Image - Invalid Parameter
BS: Failed to start OpenCore from disk - Invalid Parameter

**Comment by zearp** [comment]
I wonder how you end up with those messages. Do they remain if you reset NVRAM? I've not run into these messages. What exactly did you change from the EFI o the repo? Cuz I use an exact clone of the repo on my machines and just change the serials with a simpel bash script. It's how I keep the EFI in sync on my machines. Can you share the config file or the whole EFI? Remove serials as its public here.

**Comment by zearp** [comment]
I wonder how you end up with those messages. Do they remain if you reset NVRAM? I've not run into these messages. What exactly did you change in the EFI compared to the repo? Cuz I use an exact clone of the repo on my machines and just change the serials with a simpel bash script. It's how I keep the EFI in sync on my machines. Can you share the config file or the whole EFI? Remove serials as its public here.

**Comment by davidAlaBer** [comment]
Something I have changed I can't reach selector menu to choose OS

Enviado desde mi iPhone

**Comment by davidAlaBer** [comment]
Warning message is gone after resetting NVRAM!
 

Enviado desde mi iPhone

**Comment by davidAlaBer** [comment]
[efi to test.zip](https://github.com/zearp/OptiHack/files/6719826/efi.to.test.zip)
[Old fine big sur Config.zip](https://github.com/zearp/OptiHack/files/6719828/Old.fine.big.sur.Config.zip)

**Comment by davidAlaBer** [comment]
I wonder if Monterey change in anything the almost impossible to get sleep with a dGPU like mine. remember?

**Comment by zearp** [comment]
Graphical stuff is not added or enabled by default, this has always been like that mainly so people know what's going on wen they install. Prettying up is post-install and not "mission critical" or something like that. I've always just disabled the whole picker cuz I use FileVault myself. With -v removed the boot process is very smooth cuz I also remove the Dell logo from the BIOS lol. I see an Apple logo, then login-prompt then Apple logo with loading bar and then the desktop. Who needs a graphical picker? Why would anyone need multi-boot into other operating systems? We have macOS thats all that is needed 😉

Long boot time could be to a lot of things, if you don't have verbose boot enabled you can't tell where its slowing down. You could analyse the bootlog with time stamps and see where its slows down too. A bit more work cuz the log might be big but maybe better than trying to catch the slow downs while text is scrolling by.

As for sleep, I have no ideas cuz there's too little information for me to go on. I don't own any dGPU so I depend on others reporting their findings. At the minimum I would need logs of the failing sleep and panic logs if it panics too. A thing to keep in mind is that with dGPU sometimes it matters ifs you set your BIOS to auto or external video card mode. Try out both.

I think the first thing to do is setup a PCI device again for WhateverGreen and maybe also parse some extra options to get DRM to work and to put the iGPU in compute mode. Simply removing the entry was enough previously but maybe that has changed. What dGPU do you have? Did you add any other hardware to the system? Maybe wifi/bluetooth? If so, slow boot might be due to bluetooth, there's some issues with non-Apple bluetooth cards/sticks.

I've re-added the PCI device to the config, it is also a place you can add options for DRM instead of using boot flags but for testing boot flags are fine. Can you try booting with the config as is, try sleep and let me know what happens.

Then add ```agdpmod=pikera``` to the boot flags and try again, and once more with ```agdpmod= vit9696```. It might solve the sleep issue. Let me know if there are differences and collect logs too. Also check if DRM works with any of the flags. It should in theory enable DRM but it depends on your card. If you can play back Netflix/Amazon Prime/etc DRM is working.


[config.plist.zip](https://github.com/zearp/OptiHack/files/6720044/config.plist.zip)

**Comment by davidAlaBer** [comment]
1 minute 40 seconds is sooo much time to boot. Does this make sense to you?
Something related to IO80211FamilyLegacy and AirPortBrcmNIC. I have a wifi/bluettooth PCI card from China OSX compatible. It works.

log delays:
`2021-06-27 00:23:24.324653+0200 0x880      Default     0x0                  0      0    kernel: (IO80211FamilyLegacy) com.apple.p2p: AWDL is off
2021-06-27 00:23:39.813047+0200 0x12b      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 75.674801: txpkt (MPDU) Complete
`
`2021-06-27 00:23:41.795106+0200 0x12b      Default     0x0                  0      0    kernel: (AirPortBrcmNIC) ARPT: 77.656863: txpktpend AC_BK 0 AC_BE 0 AC_VI 0 AC_VO 1 BCMC 0 ATIM 0
2021-06-27 00:23:56.340120+0200 0xbde      Default     0x0                  0      0    kernel: (AppleKeyStore) AppleKeyStore:11149:149: operation failed (sel: 7 ret: e00002bc, -1, 100000)
`

**Comment by davidAlaBer** [comment]
dGPU:
Radeon RX 570:

New config you sent me.
Set to External card in Bios, or Auto same behaviour
No Legacy rom in BIos

Go to sleep but never wakes, no signal, no screen sharing from other computer

**Comment by davidAlaBer** [comment]
agdpmod=pikera
no changes

agdpmod=vit9696
no changes

No Legacy rom in BIos
The system wakes up in black and screen sharing not available.

Yes > Legacy rom in BIos
The system goes to sleep.
The system wakes up.... but when it wakes up the resolution is bad, with artefacts, I can share screen with another computer and there the resolution is correct, when I change the res (looking for a fix) it goes to a small window around 800x600 in the middle of the screen and gets better, but unusable.

Any clue. What logs do you want?

**Comment by zearp** [comment]
Can you please open a new issue for this? Cuz it doesn't belong here and I'm almost confident it has nothing to do with the WEFI and if you revert your machine to stock 7020/9020 everything will work as good as it works for me cuz we have the same hardware. But as soo nas changes are introduced then things change of course. Thats why I asked to share any changes from the default config. Cuz I need the full picture.

There is a lot of stuff you didn't mention despite me asking. Please keep in mind I'm not here to guide people into getting their things to work with a beta OS. Anyone trying beta software should be familiar with troubleshooting and log collecting. Also some of your issues might be caused by actual bugs or caused because some hardware is no longer supported or requires additional configuration/fixes for Monterey. 

For sleep legacy roms must be left enabled, that should be your base line. Then instead of disabling that and breaking things try and fix the resolution issue on wake. Thats the way to go. I really wish you would've told me all the changes to your setup vs the a default stock 7020/9020. Cuz that PCI card could also be the cause of sleep issues, it may need APSM disabled or some other fix. 

If I were you I would remove both PCI cards and bring your machine back to stock, then with it exactly the same as I have check if Monterey works like it does for me. I would say thats almost a crucial step. If only to serve as sanity check. It would also have exposed the cause of some issues like your boot delay. If you go to stock first and then add/apply your changes from the default setup one by one you spot it right away that after you added PCI card X something stopped working or became slow.


If I would get your machine in for repair my process would be like this:

- Remove PCI wifi card
- Remove dGPU
- Test if everything works as it should with the stock config

Depending on this results I take the next steps.

If everything works as it should with the stock config, including BIOS options then add one thing at the time and make it work.

- Add dGPU back
- Change config: set iGPU platfor-id to compute mode
- Check in Hackintool if compute mode is working (VDADecoder/Metal Headless)
- If not working, go back to config and remove whole PCI section like before and check again
- I still not in compute mode, look online and see if anyone else has this and also test if it does work in a different macOS with the same EFI to rule out if its related to Monterey or not
- If the compute mode can't be made work properly for whatever reason move on to the DRM boot flags
- Try each boot flag with Netflix or similar, if it works great if it doesn't,t same as above, check online, etc
- Then try sleep, you say it works but the resolution is off that would mean to look online again
- Search for your card and see if anyone else has it, try their solutions if any if nothing broaden your search etc

And thats just for dGPU. Once you tried it all you can try the Airport card, if the dGPU ends up being useless either because it doesn't work properly, breaks resolution on wake or if DRM isn't working remove the card for the time being as its a cause of issues and must be taken out of the pool of potential trouble makers. If it works partially also take it out for the time being. Only leave it in when it works 100% and doesn't break anything.

Now you can try there Airport card with the dGPU out of the way.

What Airport card do you have? Some may need some extra configuration for Monterey. Some Apple cards I use needed fixes for Monterey and bluetooth is having issues for everybody. Including startup delays. On my NUC leaving bluetooth kexts enabled stalls the boot 5-10 minutes. This is beta software after all. If want a stable macOS stay away from this until its released in a few months. The card might need APSM disabled in Monterey. There are quite some possibilities here again, which also depends on what type of card you have, the connection and the card itself of course. Monterey may have dropped support for your model and needs additional config fixes or maybe can't be made to work at all.

Another thing for Airport or any wifi/bt card is the bluetooth usb part. How is that connected? Did you connect it to an internal header on the motherboard or a cable to the outside if you don't have the internal connector and is that port mapped and set to type 255 (internal) correctly? What's the exact model of the card?

As mention on the repo, sleeps logs (or parts of it) can be seen by running ```log show --style syslog | fgrep "[powerd:sleepWake]"```.

If you need your machine to work then use a previous version of macOS if you don't have any issues there. Only use beta software if you're up for, and know how to rule out causes and gather (debug) logs and such. I can't really guide anyone like I did now cuz I won;'t have any spare time left. Normally I only help with issues caused by the EFI in normal macOS versions. You setup has changes and this beta macOS software. If all your things work in Big Sur I would stay on that if you need your machine for work. Use the beta's if like to be on the cutting edge and don't mind spending (lots) of time figuring things out, rebooting countless of times, reinstall macOS over and over to test and mess about.

I think I have covered pretty much everything in this response and my next one won't be as in-depth. Take your time to troubleshoot and play around and when opening your new issue to share results/etc include as much as possible, including the things I've asked for cuz else I can;'t really do anything. And honestly after this I won't be able to do much more cuz I laid it all out above.

I can't put in this much time all the time cuz I my time is limited and I also believe people should know the troubleshooting stuff outlined in this post when using beta software. If all someone needs is a drop-in EFI then by all means use my repo but use a stable macOS version with it.

This isn't a dig at you but more in general. Cuz I worry if other people see I guide one person they will also open issues expecting me to do the same and before you know it I spend all my spare time helping others with things they should know before even starting with whatever they started doing. I been in there before and it's not a good place to be. I'm just one person with limited time wanting to share with the world this fun hobby but I'm not here to provide post-install support or any support for that matter.

Issues are for things caused or very closely related to the EFI not for me to write step-by-step guides for people to get their 3rd party cards to work. There are much better places for that with hundreds of people willing to help anyone, including those who are brand new to this. Forums, Discord and maybe Reddit are better places than Github issues.

**Comment by zearp** [comment]
Anyone with problems relating to this PR please open a new issue to keep things tidy.

**Comment by zearp** [comment]
Updating to Monterey beta 2 via App Store went flawlessly.

**Comment by zearp** [comment]
Beta 3: http://swcdn.apple.com/content/downloads/02/08/071-63739-A_G5RYVW5JHT/dfz5gp3s0jm9vl7m30oewq141zkpv8edr8/InstallAssistant.pkg

**Comment by zearp** [comment]
Beta 3 notes:

- Installing from within macOS made the full installer download the full installer again! Solved by installing from usb
- Safari tab preview hover bug is fixed and they reverted the UI changes, no more shared address bar
- After every beta update Apple opts you back into sharing data, this might be a feature not a bug haha

**Pull request merged**
